"""
Exceptions and warnings for the RMM system
"""
from . import system as _sys
from ..base import OARException

class RMMException(OARException):
    """
    an exception occurring while interacting with the RMM system
    """

    def __init__(self, message=None, cause=None):
        if not message and not cause:
            message = "Unknown RMM exception occurred"
        super(RMMException, self).__init__(message, cause, _sys)

class RMMWarning(Warning):
    """
    a base class for warnings generated by the preservation system
    """
    def __init__(self, msg=None, cause=None):
        """
        create the base warning.

        :param msg    str:  a specific warning message
        :param cause Exception:  a caught but handled Exception that is the 
                            cause of the warning
        :param sys SystemInfo:  a SystemInfo instance that can provide 
                            information as to the cause of the 
        """
        self.cause = cause
        self.sys = _sys
        Warning.__init__(self, msg)

class RMMStateException(RMMException):
    """
    a class indicating that the RMM system or environment is in 
    an uncorrectable state preventing proper processing
    """
    pass

class DatabaseStateError(RMMStateException):
    """
    a class indicating that the RMM database is in 
    an uncorrectable state preventing proper processing.  An example 
    would be detecting multiple records with the same unique key value. 
    """
    pass

