#! /bin/bash
#
# makedist:  build the package's distributions
#
# This package only provides one distribution: pdr-nerdm
#
set -e
prog=`basename $0`
execdir=`dirname $0`
[ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
PACKAGE_DIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`
SOURCE_DIR=$PACKAGE_DIR

# Update this list with the names of the individual component names
# 
DISTNAMES="pdr-nerdm nerdm-docs"

# this is needed because realpath is not on macs
function realpath {
    if [ -d "$1" ]; then
        (cd $1 && pwd)
    elif [ -f "$1" ]; then
        file=`basename $1`
        parent=`dirname $1`
        realdir=`(cd $parent && pwd)`
        echo "$realdir/$file"
    elif [[ $1 = /* ]]; then
        echo $1
    else
        echo "$PWD/${1#./}"
    fi
}

# handle command line options
while [ "$1" != "" ]; do 
  case "$1" in
    --list|-l)
        echo "Available distributions: $DISTNAMES"
        exit 0
        ;;
    --dist-dir=*)
        DIST_DIR=`echo $1 | sed -e 's/[^=]*=//'`
        ;;
    --dist-dir)
        shift
        DIST_DIR=$1
        ;;
    --source-dir=*|--dir=*)
        SOURCE_DIR=`echo $1 | sed -e 's/[^=]*=//'`
        ;;
    -d|--dir|--source-dir)
        shift
        SOURCE_DIR=$1
        ;;
    --cache-dir=*)
        CACHE_DIR=`echo $1 | sed -e 's/[^=]*=//'`
        # NOTE: CACHE_DIR is ignored
        ;;
    -c|--cache-dir)
        shift
        CACHE_DIR=$1
        # NOTE: CACHE_DIR is ignored
        ;;
    -*)
        echo "$prog: unsupported option:" $1
        false
        ;;
    pdr-nerdm|nerdm-docs)
        # assuming just two distributions
        build_dist="$build_dist $1"
        true
        ;;
    *)
        echo "${prog}: ${1}: unrecognized distribution name"
        false
        ;;
  esac
  shift
done
[ -n "$build_dist" ] || build_dist=$DISTNAMES
echo '#' Building $build_dist

true ${DIST_DIR:=$SOURCE_DIR/dist}
BUILD_DIR=$SOURCE_DIR/dist
mkdir -p $BUILD_DIR $DIST_DIR

# set the current version.  This will inject the version into the code, if 
# needed.
#
# set -x
echo '+' scripts/setversion.sh
scripts/setversion.sh
[ -n "$PACKAGE_NAME" ] || PACKAGE_NAME=`cat VERSION | awk '{print $1}'`
version=`cat VERSION | awk '{print $2}'`
vers4fn=`echo $version | sed -re 's#[/\s]+#_#g'`

echo '+' PACKAGE_NAME=$PACKAGE_NAME
echo '+' version=$version

args=
[ -z "$CACHE_DIR" ] || args="$args --cache-dir=`realpath $CACHE_DIR`"
[ -z "$DIST_DIR" ] || args="$args --dist-dir=`realpath $DIST_DIR`"
[ -z "$SOURCE_DIR" ] || args="$args --source-dir=`realpath $SOURCE_DIR`"

if (echo $build_dist | grep -qs pdr-nerdm); then
    echo '+' $execdir/makedist.pdr $args pdr-nerdm
    $execdir/makedist.pdr $args pdr-nerdm
fi
if (echo $build_dist | grep -qs nerdm-docs); then
    echo '+' $execdir/makedist.nerdmdocs $args nerdm-docs
    $execdir/makedist.nerdmdocs $args nerdm-docs
fi

